M48
; DRILL file {KiCad 8.0.6} date 2025-02-05T09:38:41+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-05T09:38:41+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X75.0Y-57.0
X75.0Y-152.0
X103.4Y-57.0
X103.4Y-152.0
T2
X82.855Y-57.585
X95.555Y-57.585
M30
